// <auto-generated />
using System;
using ElectronicsComponentWarehouse.Infrastructure.Data.ElectronicsComponentWarehouse.Infrastructure.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicsComponentWarehouse.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4921),
                            Description = "Микроконтроллеры и микропроцессоры",
                            Name = "Microcontrollers",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4922)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4926),
                            Description = "Микросхемы и интегральные схемы",
                            Name = "Microchips",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4926)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4927),
                            Description = "Полевые транзисторы (MOSFET)",
                            Name = "Mosfets",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4928)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4929),
                            Description = "Конденсаторы",
                            Name = "Capacitors",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4929)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4930),
                            Description = "Резисторы",
                            Name = "Resistors",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4930)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4931),
                            Description = "Диоды и стабилитроны",
                            Name = "Diodes",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4932)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4932),
                            Description = "Биполярные транзисторы",
                            Name = "Transistors",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4933)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4934),
                            Description = "Разъемы и коннекторы",
                            Name = "Connectors",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4934)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4935),
                            Description = "Датчики и сенсоры",
                            Name = "Sensors",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4936)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4937),
                            Description = "Дисплеи и индикаторы",
                            Name = "Displays",
                            UpdatedAt = new DateTime(2026, 1, 13, 8, 8, 25, 434, DateTimeKind.Utc).AddTicks(4937)
                        });
                });

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatasheetLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinimumStockLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StorageCellNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Manufacturer");

                    b.HasIndex("Name");

                    b.HasIndex("StockQuantity");

                    b.HasIndex("StorageCellNumber")
                        .IsUnique();

                    b.ToTable("Components", null, t =>
                        {
                            t.HasCheckConstraint("CK_Component_MinimumStockLevel", "[MinimumStockLevel] >= 0");

                            t.HasCheckConstraint("CK_Component_StockQuantity", "[StockQuantity] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(245),
                            DatasheetLink = "https://docs.arduino.cc/resources/datasheets/A000066-datasheet.pdf",
                            Description = "Микроконтроллерная плата на базе ATmega328P",
                            LastUpdated = new DateTime(2026, 1, 12, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(253),
                            Manufacturer = "Arduino",
                            MinimumStockLevel = 5,
                            ModelNumber = "A000066",
                            Name = "Arduino Uno R3",
                            StockQuantity = 25,
                            StorageCellNumber = "A-01-01",
                            UnitPrice = 22.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 12, 19, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(256),
                            DatasheetLink = "https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32_datasheet_en.pdf",
                            Description = "Модуль WiFi+Bluetooth на ESP32",
                            LastUpdated = new DateTime(2026, 1, 13, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(256),
                            Manufacturer = "Espressif",
                            MinimumStockLevel = 8,
                            ModelNumber = "ESP32-WROOM-32",
                            Name = "ESP32 DevKit",
                            StockQuantity = 18,
                            StorageCellNumber = "A-01-02",
                            UnitPrice = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 11, 14, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(259),
                            Description = "Резистор 10 кОм, 0.25 Вт, 5%",
                            LastUpdated = new DateTime(2026, 1, 8, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(259),
                            Manufacturer = "Yageo",
                            MinimumStockLevel = 200,
                            ModelNumber = "CFR-25JB-10K",
                            Name = "Resistor 10kΩ 1/4W",
                            StockQuantity = 1000,
                            StorageCellNumber = "B-02-01",
                            UnitPrice = 0.02m
                        });
                });

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 14, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3587),
                            Email = "admin@warehouse.local",
                            FullName = "Администратор Системы",
                            IsActive = true,
                            LastLoginAt = new DateTime(2026, 1, 12, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3589),
                            PasswordHash = new byte[] { 65, 100, 109, 105, 110, 49, 50, 51, 33 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 95, 102, 111, 114, 95, 97, 100, 109, 105, 110 },
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 14, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3596),
                            Email = "user@warehouse.local",
                            FullName = "Обычный Пользователь",
                            IsActive = true,
                            LastLoginAt = new DateTime(2026, 1, 12, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3597),
                            PasswordHash = new byte[] { 85, 115, 101, 114, 49, 50, 51, 33 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 95, 102, 111, 114, 95, 117, 115, 101, 114 },
                            Role = "User",
                            Username = "user"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 14, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3601),
                            Email = "manager@warehouse.local",
                            FullName = "Менеджер Склада",
                            IsActive = true,
                            LastLoginAt = new DateTime(2026, 1, 12, 8, 8, 25, 435, DateTimeKind.Utc).AddTicks(3601),
                            PasswordHash = new byte[] { 77, 97, 110, 97, 103, 101, 114, 49, 50, 51, 33 },
                            PasswordSalt = new byte[] { 115, 97, 108, 116, 95, 102, 111, 114, 95, 109, 97, 110, 97, 103, 101, 114 },
                            Role = "User",
                            Username = "manager"
                        });
                });

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.Category", b =>
                {
                    b.HasOne("ElectronicsComponentWarehouse.Domain.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.Component", b =>
                {
                    b.HasOne("ElectronicsComponentWarehouse.Domain.Entities.Category", "Category")
                        .WithMany("Components")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ElectronicsComponentWarehouse.Domain.Entities.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
